#!/usr/bin/env python3
"""Executor value metrics: extract flowforge-implementer session metrics from
the local opencode SQLite DB into an append-only observations.md.

Authorities:
- design: docs/proposals/executor-value-measurement/design.md (d-extraction, d-cost)
- requirements: docs/proposals/executor-value-measurement/requirements.md

Zero third-party dependencies (python3 stdlib only). The DB is always opened
read-only via a ``file:...?mode=ro`` URI; observations.md is append-only with
the session id as idempotency key.

Usage:
    python3 scripts/executor_metrics.py extract \
        --db ~/.local/share/opencode/opencode.db \
        --project tangram-v2 \
        --out docs/proposals/executor-value-measurement/observations.md \
        [--since <epoch-ms|ISO8601>] \
        [--epochs "name:<T,name:T1-T2,name:>T2"] \
        [--price-override '{"flash":[in,out,cacheR],...}']

    python3 scripts/executor_metrics.py report \
        --obs docs/proposals/executor-value-measurement/observations.md \
        [--out docs/proposals/executor-value-measurement/report.md] \
        [--epochs "name:<T,name:T1-T2,name:>T2"] \
        [--project-root /path/to/target-repo] \
        [--price-override '{"flash":[in,out,cacheR],...}']

Semantics pinned by the design authority:
- verdict per bash part (output text): ``BUILD SUCCESSFUL`` -> ok;
  ``BUILD FAILED`` -> fail; ``exit code N`` with N != 0 -> fail; otherwise
  unknown. unknown neither increments nor resets a fail streak.
- status: first ``STATUS:\\s*(\\w+)`` match in the session's LAST text part
  (ordered by time_created); missing -> ``none``.
- ticket: first ``proposals/<p>/issues/<id>.md`` match in the FIRST text part.
- bash commands are normalized (trim, collapse whitespace, truncate to 120
  chars) before counting repetitions.
- epoch bounds are strict (``<T``, ``>T``); ranges ``T1-T2`` are inclusive
  (a ts exactly at a boundary belongs to the right, closed range form).
- est_cost uses tier proxy prices $/M (input, output, cache read); tier is
  ``flash`` when the model id contains "flash", else ``flagship``.

Report semantics (ticket 02; design d-epoch / d-strata / d-cost):
- observations.md is read-only for report; report.md is fully replaced.
- epochs come from ``--epochs`` (never guessed); sessions outside every
  bound are ``unclassified``.
- strata are the objective ticket proxy: change-bullet count plus
  evidence-cmd family — L = >= 4 change bullets or any integrationTest /
  E2E / --rerun command; S = <= 2 change bullets with unit-level commands
  only (test --tests / pnpm test / go test / unittest / pytest class);
  M otherwise. Tickets that cannot be resolved under --project-root are
  ``unknown`` and counted in the report.
- runaway = steps > 150 or rep_max > 10 or dur_min > 30 (any one).
- medians use statistics.median (even n = mean of the two middle values).

Gate semantics (ticket 03; design d-decision-gates — pre-registered):
- gates consume observations rows + the aggregation only, never the DB
  (report stays offline-rerunnable); only the ``hardened`` epoch gates.
- observation window (local time): 2026-09-14 00:00 -> 2026-09-20 23:59;
  remaining days = window last day - report run day.
- G1 loop safety: hardened runaway events = 0 -> pass; any -> fail (alarm);
  hardened empty -> insufficient-n.
- G2 economics per stratum: flash cost median < flagship median x 0.7 with
  n >= 5 per side -> pass; ratio >= 0.7 -> fail (>= 2x -> rollback,
  otherwise extend observation); n < 5 -> insufficient-n.
- G3 duration per stratum: flash dur median <= flagship median x 1.5 ->
  pass; recorded only, never triggers rollback by itself.
- G4 recurrence circuit-break: hardened session with rep_max >= 20 or
  steps >= 400 (right-inclusive) -> fail (immediate-rollback alarm).
- closeout writes DECISION.md (three-way conclusion template) from the
  final report; rules change only via design d-decision-gates revision.
"""

import argparse
import json
import os
import re
import sqlite3
import statistics
import sys
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_DB = Path.home() / ".local/share/opencode/opencode.db"

TICKET_RE = re.compile(r"proposals/[\w.-]+/issues/[\w.-]+\.md")
STATUS_RE = re.compile(r"STATUS:\s*(\w+)")
EXIT_CODE_RE = re.compile(r"exit code (\d+)")
WS_RE = re.compile(r"\s+")

# $/M proxy prices per tier: (input, output, cache_read) — requirement authority.
DEFAULT_PRICES = {
    "flash": (0.30, 2.50, 0.075),
    "flagship": (0.60, 2.20, 0.113),
}

COLUMNS = ("session", "ts", "dur_min", "model", "provider", "ticket", "epoch",
           "steps", "tools", "bash_n", "rep_max", "fail_streak",
           "in_tok", "out_tok", "cacheR_tok", "est_cost", "status")

HEADER_LINES = (
    "# Executor value observations",
    "",
    "Append-only per-session metrics for `flowforge-implementer` sessions, generated by",
    "`scripts/executor_metrics.py extract` (authorities: design.md d-extraction/d-cost).",
    "Do not edit rows by hand; re-run extract to append — the session id is the idempotency",
    "key. est_cost is a tier proxy price estimate, not an invoice figure.",
    "",
    "| " + " | ".join(COLUMNS) + " |",
    "|" + "---|" * len(COLUMNS),
)


class MetricsError(Exception):
    """User-facing extraction error (non-zero exit)."""


def open_ro(db_path):
    path = Path(db_path).expanduser()
    if not path.exists():
        raise MetricsError(f"database not found: {path}")
    uri = "file:" + urllib.parse.quote(str(path), safe="/:") + "?mode=ro"
    try:
        return sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        raise MetricsError(f"cannot open database read-only: {path}: {exc}") from exc


def check_schema(conn):
    try:
        names = {row[0] for row in
                 conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    except sqlite3.DatabaseError as exc:
        raise MetricsError(f"not a SQLite database: {exc}") from exc
    missing = {"session", "part"} - names
    if missing:
        raise MetricsError(
            "opencode DB missing table(s): " + ", ".join(sorted(missing)))


def classify_verdict(output_text):
    """ok / fail / unknown for one bash part's output text."""
    if not isinstance(output_text, str):
        return "unknown"
    if "BUILD SUCCESSFUL" in output_text:
        return "ok"
    if "BUILD FAILED" in output_text:
        return "fail"
    match = EXIT_CODE_RE.search(output_text)
    if match and int(match.group(1)) != 0:
        return "fail"
    return "unknown"


def normalize_command(cmd):
    """Trim, collapse whitespace, truncate to 120 chars (requirement constraint)."""
    return WS_RE.sub(" ", cmd.strip())[:120]


def parse_epochs(spec):
    """Parse "name:<T,name:T1-T2,name:>T2" into [(name, lo, hi)] bounds (ms)."""
    if not spec:
        return None
    epochs = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        name, sep, bound = chunk.partition(":")
        if not sep:
            raise MetricsError(f"bad epoch chunk, expected name:bound: {chunk!r}")
        name, bound = name.strip(), bound.strip()
        try:
            if bound.startswith("<"):
                epochs.append((name, None, int(bound[1:])))  # ts < hi
            elif bound.startswith(">"):
                epochs.append((name, int(bound[1:]) + 1, None))  # ts > bound
            else:
                lo, sep2, hi = bound.partition("-")
                if not sep2:
                    raise ValueError(bound)
                epochs.append((name, int(lo), int(hi) + 1))  # T1 <= ts <= T2
        except ValueError as exc:
            raise MetricsError(
                f"bad epoch bound, expected <T, T1-T2 or >T: {chunk!r}") from exc
    return epochs or None


def epoch_label(ts, epochs):
    if not epochs:
        return "-"
    for name, lo, hi in epochs:
        if lo is not None and ts < lo:  # range lower bound inclusive
            continue
        if hi is not None and ts >= hi:  # '< T' strict, range upper inclusive
            continue
        return name
    return "-"


# --- report: epoch / strata / runaway constants (ticket 02; single source) ---

UNCLASSIFIED = "unclassified"
STRATA_ORDER = ("S", "M", "L", "unknown")
STRATA_S_MAX_CHANGES = 2   # S: changes <= 2 AND all evidence cmds unit-level
STRATA_L_MIN_CHANGES = 4   # L: changes >= 4 OR any heavy evidence cmd
RUNAWAY_STEPS = 150        # runaway: steps > 150 ...
RUNAWAY_REP_MAX = 10       # ... or rep_max > 10 ...
RUNAWAY_DUR_MIN = 30.0     # ... or dur_min > 30 (any one)

# --- decision gates (ticket 03; design d-decision-gates — pre-registered) ---
# Gate rules were registered BEFORE the observation window opened; the report
# only prints the current verdict against them. Changing a rule means revising
# the design authority first (d-decision-gates) — never this script alone.

HARDENED_EPOCH = "hardened"  # only the hardened epoch gates (d-epoch: the
#                             pre-hardening / provider-switch epochs are baselines)
GATE_MIN_N = 5               # per-side minimum n for a hard verdict
G2_COST_RATIO = 0.7          # flash cost median < flagship median x 0.7
G2_ROLLBACK_RATIO = 2.0      # design G2: fail with ratio >= 2x -> rollback
G3_DUR_RATIO = 1.5           # flash dur median <= flagship median x 1.5
G4_REP_MAX = 20              # circuit-break: rep_max >= 20 (right-inclusive)
G4_STEPS = 400               # circuit-break: steps >= 400 (right-inclusive)
GATE_PASS = "pass"
GATE_FAIL = "fail"
GATE_INSUFFICIENT = "insufficient-n"
GATE_NOT_TRIGGERED = "not-triggered"
_GATE_SEVERITY = {GATE_PASS: 0, GATE_NOT_TRIGGERED: 0,
                  GATE_INSUFFICIENT: 1, GATE_FAIL: 2}

# Pre-registered observation window (design d-decision-gates, local time):
# 2026-09-14 00:00 -> 2026-09-20 23:59; remaining days = last day - run day.
OBS_WINDOW_START = datetime(2026, 9, 14, 0, 0)
OBS_WINDOW_END = datetime(2026, 9, 20, 23, 59)
OBS_WINDOW_LAST_DAY = OBS_WINDOW_END.date()

# ticket-file shape proxies for the strata classification (objective, no human
# rating): change bullets, inline command code spans, and cmd families.
CHANGE_LINE_RE = re.compile(r"(?m)^\s*- \[[ x]\]\s")
CODE_SPAN_RE = re.compile(r"`([^`\n]+)`")
# a code span counts as a command if it names a known runner
COMMAND_SPAN_RE = re.compile(
    r"gradlew|gradle|pnpm|npm|yarn|go\s+(?:test|build|vet)|python|pytest|unittest|make|mvn|cargo",
    re.IGNORECASE)
# unit-level acceptance cmds (design d-strata family: test --tests / pnpm test /
# go test ./pkg; unittest/pytest are the same class for this repo's scripts)
UNIT_CMD_RE = re.compile(
    r"test\s+--tests|pnpm\s+test|npm\s+test|yarn\s+test|go\s+test\b|unittest|pytest",
    re.IGNORECASE)
# heavy acceptance cmds -> L regardless of change count (design d-strata)
HEAVY_CMD_RE = re.compile(r"integrationTest|E2E|--rerun")

# directories never containing tickets; pruned from the project-root walk
GLOB_SKIP_DIRS = {".git", "node_modules", "build", "dist", "out", "target",
                  ".gradle", ".next", "vendor"}


def report_epoch(ts, epochs):
    """Epoch label for a report row; uncovered (or no spec) -> unclassified."""
    if not epochs:
        return UNCLASSIFIED
    label = epoch_label(ts, epochs)
    return UNCLASSIFIED if label == "-" else label


def ts_ms(iso):
    """ISO8601 observations ts -> epoch ms."""
    try:
        dt = datetime.fromisoformat(iso)
    except (TypeError, ValueError) as exc:
        raise MetricsError(f"bad ts value in observations row: {iso!r}") from exc
    if dt.tzinfo is None:
        dt = dt.astimezone()
    return int(dt.timestamp() * 1000)


def _split_table_line(line):
    return [c.strip().replace("\\|", "|")
            for c in re.split(r"(?<!\\)\|", line.strip().strip("|"))]


def _is_separator(cells):
    return bool(cells) and all(set(c) <= {"-", " ", ":"} for c in cells)


def parse_obs_rows(text):
    """Parse the observations.md metrics table (header-driven) into dicts.

    The header row supplies the column order (all COLUMNS must be present);
    values are typed: ints for counters/tokens, floats for dur_min/est_cost.
    """
    header = None
    rows = []
    for lineno, line in enumerate(text.splitlines(), 1):
        if not line.startswith("|"):
            continue
        cells = _split_table_line(line)
        if _is_separator(cells):
            continue
        if header is None:
            header = cells
            continue
        if len(cells) != len(header):
            raise MetricsError(
                f"observations row {lineno}: expected {len(header)} columns "
                f"(header {header[0]}|...), got {len(cells)}")
        rows.append(dict(zip(header, cells)))
    if header is None:
        raise MetricsError("observations file has no metrics table header")
    missing = [c for c in COLUMNS if c not in header]
    if missing:
        raise MetricsError(
            "observations table missing column(s): " + ", ".join(missing))
    for row in rows:
        for col in ("steps", "tools", "bash_n", "rep_max", "fail_streak",
                    "in_tok", "out_tok", "cacheR_tok"):
            try:
                row[col] = int(row[col])
            except (TypeError, ValueError) as exc:
                raise MetricsError(
                    f"observations row {row['session']!r}: column {col} is not "
                    f"an integer: {row[col]!r}") from exc
        for col in ("dur_min", "est_cost"):
            try:
                row[col] = float(row[col])
            except (TypeError, ValueError) as exc:
                raise MetricsError(
                    f"observations row {row['session']!r}: column {col} is not "
                    f"a number: {row[col]!r}") from exc
    return rows


def count_change_lines(ticket_text):
    """Number of `- [ ]` / `- [x]` Change bullets in a ticket file."""
    return len(CHANGE_LINE_RE.findall(ticket_text))


def ticket_cmds(ticket_text):
    """Command-shaped strings from a ticket file: inline code spans and
    `- cmd:` values (objective evidence-cmd proxy)."""
    cmds = [m.group(1) for m in CODE_SPAN_RE.finditer(ticket_text)]
    return [c for c in cmds if COMMAND_SPAN_RE.search(c)]


def classify_stratum_text(ticket_text):
    """S / M / L objective proxy (design d-strata):
    L = changes >= 4 or any heavy cmd (integrationTest / E2E / --rerun);
    S = changes <= 2 and every command span is unit-level;
    M = the rest."""
    n_changes = count_change_lines(ticket_text)
    cmds = ticket_cmds(ticket_text)
    if n_changes >= STRATA_L_MIN_CHANGES or any(HEAVY_CMD_RE.search(c) for c in cmds):
        return "L"
    if n_changes <= STRATA_S_MAX_CHANGES and cmds and \
            all(UNIT_CMD_RE.search(c) for c in cmds):
        return "S"
    return "M"


def glob_ticket_files(project_root):
    """`**/issues/*.md` under project_root, pruning dependency/build dirs."""
    found = []
    for dirpath, dirnames, filenames in os.walk(project_root):
        dirnames[:] = [d for d in dirnames if d not in GLOB_SKIP_DIRS]
        if os.path.basename(dirpath) == "issues":
            for fn in sorted(filenames):
                if fn.endswith(".md"):
                    found.append(Path(dirpath) / fn)
    return sorted(found)


def resolve_strata(rows, project_root):
    """Map each observation row to its stratum via the ticket file under
    project_root (suffix match on the ticket path). Returns
    (session -> stratum, unresolved_count); unresolvable tickets (and the
    no-project-root case) are `unknown` (design d-strata)."""
    strata = {}
    unresolved = 0
    if not project_root:
        for row in rows:
            strata[row["session"]] = "unknown"
        return strata, len(rows)
    root = Path(project_root).expanduser()
    ticket_files = glob_ticket_files(root) if root.is_dir() else []
    cache = {}

    def stratum_for_ticket(ticket):
        if ticket == "-":
            return "unknown"
        matches = [p for p in ticket_files if p.as_posix().endswith("/" + ticket)]
        if not matches:
            return "unknown"
        path = matches[0]
        if path not in cache:
            try:
                cache[path] = classify_stratum_text(
                    path.read_text(encoding="utf-8", errors="replace"))
            except OSError:
                cache[path] = "unknown"
        return cache[path]

    for row in rows:
        st = stratum_for_ticket(row["ticket"])
        strata[row["session"]] = st
        if st == "unknown":
            unresolved += 1
    return strata, unresolved


def tier_of(model_id):
    """flash when the model id contains 'flash', else flagship (d-cost)."""
    return "flash" if "flash" in model_id.lower() else "flagship"


def effective_prices(override=None):
    """Merged price table: proxy defaults with --price-override tiers
    replaced as whole [in, out, cacheR] triples."""
    prices = dict(DEFAULT_PRICES)
    prices.update(override or {})
    return prices


def est_cost_tokens(ti, to, tcr, prices, tier):
    """est_cost from raw token counts (design d-cost formula, single site)."""
    pin, pout, pcr = prices[tier]
    return round(ti / 1e6 * pin + to / 1e6 * pout + tcr / 1e6 * pcr, 4)


def is_runaway(row):
    """Out-of-control session: any ONE of the three pinned thresholds."""
    return (row["steps"] > RUNAWAY_STEPS
            or row["rep_max"] > RUNAWAY_REP_MAX
            or row["dur_min"] > RUNAWAY_DUR_MIN)


def est_cost_for(row, prices):
    """Recompute a session's est_cost from its token columns and tier price."""
    return est_cost_tokens(row["in_tok"], row["out_tok"], row["cacheR_tok"],
                           prices, tier_of(row["model"]))


def cell_stats(cell_rows, prices):
    """Aggregates for one (epoch, stratum) cell over its session rows."""
    costs = [est_cost_for(r, prices) for r in cell_rows]
    total = sum(costs)
    cache_cost = sum(r["cacheR_tok"] / 1e6 * prices[tier_of(r["model"])][2]
                     for r in cell_rows)
    flash = [c for c, r in zip(costs, cell_rows)
             if tier_of(r["model"]) == "flash"]
    flagship = [c for c, r in zip(costs, cell_rows)
                if tier_of(r["model"]) == "flagship"]
    return {
        "n": len(cell_rows),
        "dur_med": statistics.median(r["dur_min"] for r in cell_rows),
        "cost_med": statistics.median(costs),
        "cache_share": (cache_cost / total) if total > 0 else 0.0,
        "runaway": sum(1 for r in cell_rows if is_runaway(r)),
        "flash_n": len(flash),
        "flash_med": statistics.median(flash) if flash else None,
        "flagship_n": len(flagship),
        "flagship_med": statistics.median(flagship) if flagship else None,
    }


def aggregate_cells(rows, epochs, strata, prices):
    """Group rows by report epoch × stratum.

    Returns {epoch: {"cells": {stratum: stats}, "status": {status: n}, "n": N}}
    keyed by epoch spec names plus UNCLASSIFIED for uncovered sessions."""
    grouped = {}
    for row in rows:
        ep = report_epoch(ts_ms(row["ts"]), epochs)
        bucket = grouped.setdefault(ep, {"cells": {}, "status": {}})
        st = strata.get(row["session"], "unknown")
        bucket["cells"].setdefault(st, []).append(row)
        bucket["status"][row["status"]] = bucket["status"].get(row["status"], 0) + 1
    out = {}
    for ep, bucket in grouped.items():
        out[ep] = {
            "cells": {st: cell_stats(rs, prices)
                      for st, rs in bucket["cells"].items()},
            "status": bucket["status"],
            "n": sum(len(rs) for rs in bucket["cells"].values()),
        }
    return out


def _fmt_dur(x):
    return f"{x:.2f}".rstrip("0").rstrip(".") or "0"


def _fmt_cost(x):
    return f"{x:.4f}"


# --- decision gate evaluation (consumes observations rows + the ticket 02
# aggregation only — never the DB, so report stays offline-rerunnable) ---

def _gate(gate, verdict, detail):
    return {"gate": gate, "verdict": verdict, "detail": detail}


def hardened_rows(rows, epochs):
    """Observation rows inside any hardened-* epoch, tagged with _epoch.
    Only hardened-* epochs gate (d-epoch: earlier epochs are baselines)."""
    result = []
    for r in rows:
        if not epochs:
            continue
        label = report_epoch(ts_ms(r["ts"]), epochs)
        if label and label.startswith(HARDENED_EPOCH):
            result.append(dict(r, _epoch=label))
    return result


def evaluate_g1(hrd, epoch_label=None):
    """G1 loop safety: runaway events in this epoch must be 0."""
    label = epoch_label or HARDENED_EPOCH
    if not hrd:
        return _gate(f"G1 loop safety ({label})", GATE_INSUFFICIENT,
                     f"{label} epoch has 0 session(s) — no valid gate sample yet")
    bad = [r for r in hrd if is_runaway(r)]
    if bad:
        ids = ", ".join(
            f"{r['session']} (steps={r['steps']}, rep_max={r['rep_max']}, "
            f"dur={_fmt_dur(r['dur_min'])}min)" for r in bad)
        return _gate(f"G1 loop safety ({label})", GATE_FAIL,
                     f"{len(bad)} runaway session(s): {ids}")
    return _gate(f"G1 loop safety ({label})", GATE_PASS,
                 f"{len(hrd)} session(s), 0 runaway "
                 f"(steps>{RUNAWAY_STEPS} or rep_max>{RUNAWAY_REP_MAX} or "
                 f"dur>{RUNAWAY_DUR_MIN:g}min)")


def _insufficient_sides(label, flash_n, flagship_n):
    """insufficient-n entry for a per-stratum gate: one side below n>=5."""
    return _gate(label, GATE_INSUFFICIENT,
                 f"flash n={flash_n}, flagship n={flagship_n} "
                 f"(need n>={GATE_MIN_N} per side)")


def _overall_gate(entries, label):
    """Worst per-stratum verdict as one overall row (fail > insufficient-n)."""
    if not entries:
        return _gate(label, GATE_INSUFFICIENT,
                     "no S/M/L session in the hardened epoch yet")
    verdict = max((e["verdict"] for e in entries),
                  key=lambda v: _GATE_SEVERITY[v])
    judged = ", ".join(e["gate"].rsplit(" ", 1)[-1] + "=" + e["verdict"]
                       for e in entries)
    return _gate(label, verdict, f"worst of judged strata: {judged}")


def evaluate_g2(agg, epoch_label=None):
    """G2 economics per stratum, consuming the report aggregation's flash /
    flagship medians inside the hardened epoch. Returns (rows, overall)."""
    label = epoch_label or HARDENED_EPOCH
    cells = (agg.get(label) or {}).get("cells") or {}
    entries = []
    for st in ("S", "M", "L"):
        if st not in cells:
            continue
        c = cells[st]
        label = f"G2 economics {st}"
        if c["flash_n"] < GATE_MIN_N or c["flagship_n"] < GATE_MIN_N:
            entries.append(_insufficient_sides(label, c["flash_n"],
                                               c["flagship_n"]))
            continue
        ratio = (c["flash_med"] / c["flagship_med"]) \
            if c["flagship_med"] else float("inf")
        base = (f"flash med {_fmt_cost(c['flash_med'])} vs flagship med "
                f"{_fmt_cost(c['flagship_med'])} x {G2_COST_RATIO} "
                f"(ratio {ratio:.2f})")
        if c["flash_med"] < c["flagship_med"] * G2_COST_RATIO:
            entries.append(_gate(label, GATE_PASS, base))
        else:
            consequence = ("rollback flagship (ratio >= "
                           f"{G2_ROLLBACK_RATIO:g}x)" if ratio >= G2_ROLLBACK_RATIO
                           else "extend observation (ratio < "
                                f"{G2_ROLLBACK_RATIO:g}x)")
            entries.append(_gate(label, GATE_FAIL,
                                 f"{base} -> {consequence}"))
    return entries, _overall_gate(entries, "G2 economics (overall)")


def evaluate_g3(hrd, strata):
    """G3 duration per stratum: flash dur median <= flagship median x 1.5
    (inclusive). Computed from hardened rows; recorded only — a G3 fail never
    triggers rollback by itself. Returns (rows, overall)."""
    entries = []
    for st in ("S", "M", "L"):
        st_rows = [r for r in hrd if strata.get(r["session"]) == st]
        if not st_rows:
            continue
        flash = [r["dur_min"] for r in st_rows if tier_of(r["model"]) == "flash"]
        flagship = [r["dur_min"] for r in st_rows
                    if tier_of(r["model"]) == "flagship"]
        label = f"G3 duration {st}"
        if len(flash) < GATE_MIN_N or len(flagship) < GATE_MIN_N:
            entries.append(_insufficient_sides(label, len(flash), len(flagship)))
            continue
        f_med, g_med = statistics.median(flash), statistics.median(flagship)
        ratio = f_med / g_med if g_med else float("inf")
        verdict = GATE_PASS if f_med <= g_med * G3_DUR_RATIO else GATE_FAIL
        entries.append(_gate(
            label, verdict,
            f"flash dur med {_fmt_dur(f_med)}min vs flagship med "
            f"{_fmt_dur(g_med)}min x {G3_DUR_RATIO} (ratio {ratio:.2f})"
            + ("; recorded only, never triggers rollback alone"
               if verdict == GATE_FAIL else "")))
    return entries, _overall_gate(entries, "G3 duration (overall)")


def evaluate_g4(hrd, epoch_label=None):
    """G4 recurrence circuit-break (pre-hardening shape recurrence):
    any hardened session with rep_max>=20 or steps>=400 (right-inclusive)
    -> fail; immediate rollback, not waiting for the window to close."""
    label = epoch_label or HARDENED_EPOCH
    hits = [r for r in hrd
            if r["rep_max"] >= G4_REP_MAX or r["steps"] >= G4_STEPS]
    if hits:
        ids = ", ".join(f"{r['session']} (rep_max={r['rep_max']}, "
                        f"steps={r['steps']})" for r in hits)
        return _gate(f"G4 circuit-break ({label})", GATE_FAIL,
                     f"pre-hardening shape recurred: {ids}")
    return _gate(f"G4 circuit-break ({label})", GATE_NOT_TRIGGERED,
                 f"{len(hrd)} session(s), none with rep_max>={G4_REP_MAX} "
                 f"or steps>={G4_STEPS}")


def evaluate_gates(rows, strata, epochs, agg):
    """All four pre-registered gates over observations + the ticket 02
    aggregation. Returns {"gates": [row...], "alarms": [str...]} — alarms
    only for G1 fail / G4 triggered on the latest hardened sub-epoch."""
    hrd = hardened_rows(rows, epochs)
    epoch_groups = {}
    for r in hrd:
        ep = r.get("_epoch", HARDENED_EPOCH)
        epoch_groups.setdefault(ep, []).append(r)
    epoch_order = [name for name, _, _ in (epochs or [])
                   if name and name.startswith(HARDENED_EPOCH)]
    for ep in sorted(epoch_groups):
        if ep not in epoch_order:
            epoch_order.append(ep)
    last_epoch = epoch_order[-1] if epoch_order else None

    gates = []
    alarms = []
    for ep in epoch_order:
        ep_rows = epoch_groups.get(ep, [])
        g1 = evaluate_g1(ep_rows, ep)
        g4 = evaluate_g4(ep_rows, ep)
        gates.append(g1)
        if ep == last_epoch:
            g2_rows, g2_overall = evaluate_g2(agg, ep)
            g3_rows, g3_overall = evaluate_g3(ep_rows, strata)
            gates += g2_rows + [g2_overall] + g3_rows + [g3_overall]
            gates.append(g4)
            if g1["verdict"] == GATE_FAIL:
                alarms.append(f"G1 loop safety FAILED ({ep}): "
                              f"{g1['detail']} -> rollback to flagship "
                              "executor and open a Fix ticket "
                              "(design d-decision-gates)")
            if g4["verdict"] == GATE_FAIL:
                alarms.append(f"G4 circuit-break TRIGGERED ({ep}): "
                              f"{g4['detail']} -> rollback to flagship "
                              "immediately, do not wait for the "
                              "observation window to close")
        else:
            gates.append(g4)
    return {"gates": gates, "alarms": alarms}


def observation_window(generated):
    """(window line, remaining days) for the pre-registered observation
    window. remaining = window last day (2026-09-20, local) - report run
    day, where the run day is the generated stamp's own local date."""
    start = OBS_WINDOW_START.astimezone()
    end = OBS_WINDOW_END.astimezone()
    run_day = datetime.fromisoformat(generated).date()
    remaining = (OBS_WINDOW_LAST_DAY - run_day).days
    if remaining > 0:
        tail = f"{remaining} day(s) remaining"
    elif remaining == 0:
        tail = "window closes today"
    else:
        tail = f"window ended {-remaining} day(s) ago"
    tz = start.strftime("%z")
    line = (f"- observation window: {start:%Y-%m-%d %H:%M} -> "
            f"{end:%Y-%m-%d %H:%M} (UTC{tz[:3]}:{tz[3:]}) — {tail}")
    return line, remaining


def render_report(rows, epochs, strata, prices, *, obs_name, epochs_spec,
                  warnings, generated=None, price_note="proxy defaults"):
    """Render the full daily report document (single \\n, UTF-8)."""
    agg = aggregate_cells(rows, epochs, strata, prices)
    gates = evaluate_gates(rows, strata, epochs, agg)
    epoch_names = [name for name, _, _ in (epochs or [])]
    if UNCLASSIFIED in agg and UNCLASSIFIED not in epoch_names:
        epoch_names.append(UNCLASSIFIED)
    if not epoch_names:
        epoch_names = [UNCLASSIFIED]
    generated = generated or datetime.now().astimezone().isoformat(
        timespec="seconds")
    window_line, _ = observation_window(generated)
    price_bits = [f"{tier} {'/'.join(str(p) for p in trio)}"
                  for tier, trio in sorted(prices.items())]

    lines = [
        "# Executor value report",
        "",
        "Daily replacement report generated by `scripts/executor_metrics.py report` —",
        "do not edit by hand: observations.md is the append-only source, this file is",
        "fully replaced on each run. est_cost is a tier proxy price estimate, not an",
        "invoice figure.",
        "",
        f"- generated: {generated}",
        f"- observations: {obs_name} ({len(rows)} sessions)",
        f"- epochs: {epochs_spec if epochs_spec else '(none — all sessions unclassified)'}",
        f"- prices ($/M in/out/cacheR, {price_note}): " + " · ".join(price_bits),
        window_line,
        "",
    ]
    for alarm in gates["alarms"]:
        lines.append(f"> ALARM: {alarm}")
    if gates["alarms"]:
        lines.append("")
    for w in warnings:
        lines.append(f"> warning: {w}")
    if warnings:
        lines.append("")

    lines += [
        "## Decision gates (pre-registered, design d-decision-gates)",
        "",
    "Verdicts compare the current data against rules registered BEFORE the",
    "observation window opened — no post-hoc inference. G1/G4 are per",
    "hardened sub-epoch; G2/G3 evaluate the latest sub-epoch only.",
    f"insufficient-n = sample below the pinned threshold (n>={GATE_MIN_N}",
        "per side per stratum).",
        "",
        "| gate | verdict | detail |",
        "|---|---|---|",
    ]
    for g in gates["gates"]:
        lines.append(f"| {g['gate']} | {g['verdict']} | {g['detail']} |")
    lines += [
        "",
        f"Pre-registered consequences: G2 fail with flash/flagship ratio >=",
        f"{G2_ROLLBACK_RATIO:g}x -> rollback flagship; otherwise -> extend",
        "observation. G3 fail is recorded only and never triggers rollback by",
        "itself. G1 fail or G4 triggered -> rollback to flagship (G4",
        "immediately, without waiting for the window to close). Closeout uses",
        "DECISION.md (three-way conclusion template).",
        "",
        "## Epoch × stratum aggregation",
        "",
        "| epoch | stratum | n | dur_med (min) | est_cost_med ($) "
        "| cacheR_cost_share | runaway_n |",
        "|---|---|---|---|---|---|---|",
    ]
    for ep in epoch_names:
        bucket = agg.get(ep)
        if not bucket or not bucket["cells"]:
            lines.append(f"| {ep} | - | 0 | - | - | - | 0 |")
            continue
        for st in STRATA_ORDER:
            if st not in bucket["cells"]:
                continue
            c = bucket["cells"][st]
            lines.append(
                f"| {ep} | {st} | {c['n']} | {_fmt_dur(c['dur_med'])} | "
                f"{_fmt_cost(c['cost_med'])} | {c['cache_share'] * 100:.1f}% | "
                f"{c['runaway']} |")
    lines += [
        "",
        f"runaway_n: sessions with steps > {RUNAWAY_STEPS} or rep_max > "
        f"{RUNAWAY_REP_MAX} or dur_min > {RUNAWAY_DUR_MIN:g} (any one).",
        "cacheR_cost_share: cache-read cost share of the cell's est_cost "
        "(Σ cacheR·P_cacheR / Σ est_cost).",
        "est_cost_med: per-ticket est_cost median (even n = mean of the two middle",
        "values), recomputed from token columns with the price table above.",
        "",
        "## Same-stratum flash vs flagship (per-ticket est_cost median)",
        "",
        "| epoch | stratum | flash n | flash est_cost_med ($) | flagship n "
        "| flagship est_cost_med ($) | flash/flagship |",
        "|---|---|---|---|---|---|---|",
    ]
    for ep in epoch_names:
        bucket = agg.get(ep)
        if not bucket:
            continue
        for st in STRATA_ORDER:
            if st not in bucket["cells"]:
                continue
            c = bucket["cells"][st]
            f_med = _fmt_cost(c["flash_med"]) if c["flash_med"] is not None else "-"
            g_med = (_fmt_cost(c["flagship_med"])
                     if c["flagship_med"] is not None else "-")
            if c["flash_med"] is not None and c["flagship_med"] is not None:
                ratio = (f"{c['flash_med'] / c['flagship_med']:.2f}"
                         if c["flagship_med"] else "inf")
            else:
                ratio = "-"
            lines.append(f"| {ep} | {st} | {c['flash_n']} | {f_med} | "
                         f"{c['flagship_n']} | {g_med} | {ratio} |")
    lines += [
        "",
        "## Session status by epoch",
        "",
        "| epoch | n | COMPLETED | BLOCKED | none | other |",
        "|---|---|---|---|---|---|",
    ]
    for ep in epoch_names:
        bucket = agg.get(ep)
        st = bucket["status"] if bucket else {}
        other = sum(v for k, v in st.items()
                    if k not in ("COMPLETED", "BLOCKED", "none"))
        lines.append(f"| {ep} | {bucket['n'] if bucket else 0} | "
                     f"{st.get('COMPLETED', 0)} | {st.get('BLOCKED', 0)} | "
                     f"{st.get('none', 0)} | {other} |")
    lines.append("")
    return "\n".join(lines)


def parse_prices(override_json):
    if not override_json:
        return None
    try:
        obj = json.loads(override_json)
    except ValueError as exc:
        raise MetricsError(f"--price-override is not valid JSON: {exc}") from exc
    if not isinstance(obj, dict):
        raise MetricsError("--price-override must be a JSON object tier -> [in, out, cacheR]")
    prices = {}
    for tier, vals in obj.items():
        if not isinstance(vals, list) or len(vals) != 3:
            raise MetricsError(f"--price-override tier {tier!r} must be [in, out, cacheR]")
        try:
            prices[tier] = tuple(float(v) for v in vals)
        except (TypeError, ValueError) as exc:
            raise MetricsError(
                f"--price-override tier {tier!r} must be numeric") from exc
    return prices


def parse_since(value):
    if value is None:
        return None
    text = value.strip()
    if re.fullmatch(r"\d{10,}", text):
        return int(text)
    try:
        dt = datetime.fromisoformat(text)
    except ValueError as exc:
        raise MetricsError(
            f"--since must be epoch-ms or ISO8601, got: {value!r}") from exc
    if dt.tzinfo is None:
        dt = dt.astimezone()
    return int(dt.timestamp() * 1000)


def fmt_ts(ms):
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).astimezone().isoformat(
        timespec="seconds")


def _session_metrics(conn, sess_row, prices, epochs):
    (sid, model_json, _directory, ti, to, tcr, tc, tu) = sess_row
    model_id = provider = "-"
    try:
        model = json.loads(model_json) if model_json else {}
        if isinstance(model, dict):
            model_id = str(model.get("id") or "-")
            provider = str(model.get("providerID") or "-")
    except ValueError:
        pass

    steps = tools = bash_n = 0
    cmd_counts = {}
    verdicts = []
    first_text = None
    last_text = None
    corrupt = 0
    query = ("SELECT data FROM part WHERE session_id=? "
             "ORDER BY time_created, rowid")
    for (raw,) in conn.execute(query, (sid,)):
        try:
            data = json.loads(raw) if raw else None
        except ValueError:
            corrupt += 1
            continue
        if not isinstance(data, dict):
            corrupt += 1
            continue
        ptype = data.get("type")
        if ptype == "step-start":
            steps += 1
        elif ptype == "tool":
            tools += 1
            if data.get("tool") != "bash":
                continue
            bash_n += 1
            state = data.get("state")
            if not isinstance(state, dict):
                state = {}
            cmd = state.get("input")
            if isinstance(cmd, dict):
                cmd = cmd.get("command")
            if isinstance(cmd, str) and cmd.strip():
                key = normalize_command(cmd)
                cmd_counts[key] = cmd_counts.get(key, 0) + 1
            output = state.get("output")
            verdicts.append(classify_verdict(output))
        elif ptype == "text":
            txt = data.get("text")
            txt = txt if isinstance(txt, str) else ""
            if first_text is None:
                first_text = txt
            last_text = txt

    streak = current = 0
    for verdict in verdicts:
        if verdict == "fail":
            current += 1
            streak = max(streak, current)
        elif verdict == "ok":
            current = 0  # unknown is skipped: neither counts nor resets (design)

    ti = ti or 0
    to = to or 0
    tcr = tcr or 0
    tier = tier_of(model_id)
    est_cost = est_cost_tokens(ti, to, tcr, prices, tier)
    ticket_match = first_text and TICKET_RE.search(first_text)
    status_match = last_text and STATUS_RE.search(last_text)
    metrics = {
        "session": sid,
        "ts": fmt_ts(tc),
        "dur_min": round((tu - tc) / 60000, 1),
        "model": model_id,
        "provider": provider,
        "ticket": ticket_match.group(0) if ticket_match else "-",
        "epoch": epoch_label(tc, epochs),
        "steps": steps,
        "tools": tools,
        "bash_n": bash_n,
        "rep_max": max(cmd_counts.values(), default=0),
        "fail_streak": streak,
        "in_tok": ti,
        "out_tok": to,
        "cacheR_tok": tcr,
        "est_cost": est_cost,
        "status": status_match.group(1) if status_match else "none",
    }
    return metrics, corrupt


def collect_metrics(conn, project, since_ms=None, prices=None, epochs=None):
    """Return (rows, corrupt_total): one metrics dict per matching session,
    ordered by time_created ascending."""
    merged = effective_prices(prices)
    query = ("SELECT id, model, directory, tokens_input, tokens_output, "
             "tokens_cache_read, time_created, time_updated FROM session "
             "WHERE agent='flowforge-implementer' AND directory LIKE ? ")
    args = ["%" + project]
    if since_ms is not None:
        query += "AND time_created >= ? "
        args.append(since_ms)
    query += "ORDER BY time_created"
    rows, corrupt_total = [], 0
    for sess_row in conn.execute(query, args):
        metrics, corrupt = _session_metrics(conn, sess_row, merged, epochs)
        corrupt_total += corrupt
        rows.append(metrics)
    return rows, corrupt_total


def format_row(metrics):
    cells = [str(metrics[col]).replace("|", "\\|").replace("\n", " ")
             for col in COLUMNS]
    return "| " + " | ".join(cells) + " |"


def append_idempotent(out_path, metrics):
    """Append rows whose session id is not already present; write the table
    header when the file is missing or empty. Returns (appended, skipped)."""
    path = Path(out_path)
    content = path.read_text(encoding="utf-8") if path.exists() else None
    existing_lines = content.splitlines() if content is not None else []
    new_rows = [m for m in metrics
                if not any(m["session"] in line for line in existing_lines)]
    with open(path, "a", encoding="utf-8", newline="\n") as handle:
        if not content:  # missing or empty file -> header
            for line in HEADER_LINES:
                handle.write(line + "\n")
        elif not content.endswith("\n"):
            handle.write("\n")
        for m in new_rows:
            handle.write(format_row(m) + "\n")
    return len(new_rows), len(metrics) - len(new_rows)


def build_parser():
    parser = argparse.ArgumentParser(
        prog="executor_metrics.py",
        description="Extract flowforge-implementer session metrics from the "
                    "opencode DB (read-only) and aggregate epoch × strata "
                    "reports.")
    sub = parser.add_subparsers(dest="command", required=True)
    extract = sub.add_parser(
        "extract", help="extract metrics and append to observations.md")
    extract.add_argument("--db", default=str(DEFAULT_DB),
                         help="opencode SQLite DB path (default: %(default)s; "
                              "always opened read-only)")
    extract.add_argument("--project", required=True,
                         help="project directory suffix, e.g. tangram-v2")
    extract.add_argument("--out", required=True,
                         help="observations.md path (append-only)")
    extract.add_argument("--since", default=None,
                         help="only sessions with time_created >= TS "
                              "(epoch ms or ISO8601; inclusive)")
    extract.add_argument("--epochs", default=None,
                         help='epoch spec "name:<T,name:T1-T2,name:>T2" in epoch ms')
    extract.add_argument("--price-override", default=None,
                         help="JSON object tier -> [in, out, cacheR] $/M "
                              "over the built-in proxy prices")
    report = sub.add_parser(
        "report", help="aggregate observations.md into report.md (replace)")
    report.add_argument("--obs", required=True,
                        help="observations.md path (read-only input)")
    report.add_argument("--out", default=None,
                        help="report.md path (default: report.md next to "
                             "--obs; fully replaced on each run)")
    report.add_argument("--epochs", default=None,
                        help='epoch spec "name:<T,name:T1-T2,name:>T2" in epoch '
                             "ms; uncovered sessions are unclassified")
    report.add_argument("--project-root", default=None,
                        help="target repo root; ticket files are resolved via "
                             "**/issues/*.md under it (missing -> unknown)")
    report.add_argument("--price-override", default=None,
                        help="JSON object tier -> [in, out, cacheR] $/M over "
                             "the built-in proxy prices; est_cost is "
                             "recomputed from token columns")
    return parser


def cmd_extract(args):
    try:
        epochs = parse_epochs(args.epochs)
        prices = parse_prices(args.price_override)
        since = parse_since(args.since)
        conn = open_ro(args.db)
        try:
            check_schema(conn)
            metrics, corrupt = collect_metrics(conn, args.project, since_ms=since,
                                               prices=prices, epochs=epochs)
        finally:
            conn.close()
    except MetricsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if corrupt:
        print(f"warn: skipped {corrupt} part row(s) with unreadable data JSON",
              file=sys.stderr)
    try:
        appended, skipped = append_idempotent(args.out, metrics)
    except OSError as exc:
        print(f"error: cannot write observations file {args.out}: {exc}",
              file=sys.stderr)
        return 1
    print(f"extract: {len(metrics)} session(s) matched, appended {appended}, "
          f"skipped {skipped} existing -> {args.out}")
    return 0


def cmd_report(args):
    try:
        epochs = parse_epochs(args.epochs)
        override = parse_prices(args.price_override)
        prices = effective_prices(override)
        obs = Path(args.obs).expanduser()
        if not obs.exists():
            raise MetricsError(f"observations file not found: {obs}")
        try:
            text = obs.read_text(encoding="utf-8")
        except OSError as exc:
            raise MetricsError(
                f"cannot read observations file {obs}: {exc}") from exc
        rows = parse_obs_rows(text)
        strata, unresolved = resolve_strata(rows, args.project_root)
    except MetricsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    warnings = []
    if not rows:
        pass
    elif not args.project_root:
        warnings.append("no --project-root given: every session classified "
                        f"stratum unknown ({len(rows)} session(s))")
    elif unresolved == len(rows):
        warnings.append(f"no ticket files matched under --project-root "
                        f"'{args.project_root}': every session stratum unknown")
    elif unresolved:
        warnings.append(f"{unresolved} session(s) with unresolvable ticket "
                        "path -> stratum unknown")
    out = Path(args.out).expanduser() if args.out else obs.parent / "report.md"
    price_note = ("overridden via --price-override" if override
                  else "proxy defaults")
    report = render_report(rows, epochs, strata, prices,
                           obs_name=str(args.obs),
                           epochs_spec=args.epochs or "",
                           warnings=warnings, price_note=price_note)
    try:
        with open(out, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(report)
    except OSError as exc:
        print(f"error: cannot write report file {out}: {exc}", file=sys.stderr)
        return 1
    counts = {}
    for st in strata.values():
        counts[st] = counts.get(st, 0) + 1
    strata_bits = " ".join(f"{st}={counts[st]}" for st in STRATA_ORDER
                           if st in counts)
    print(f"report: {len(rows)} session(s), {len(epochs or [])} epoch(s), "
          f"strata {strata_bits or 'none'} -> {out}")
    return 0


def main(argv=None):
    args = build_parser().parse_args(argv)
    if args.command == "report":
        return cmd_report(args)
    return cmd_extract(args)


if __name__ == "__main__":
    sys.exit(main())
