#!/usr/bin/env python3
"""Executor value metrics: extract flowforge-implementer session metrics from
the local opencode SQLite DB into an append-only observations.md.

Authorities:
- design: docs/proposals/executor-value-measurement/design.md (d-extraction, d-cost)
- requirements: docs/proposals/executor-value-measurement/requirements.md

Zero third-party dependencies (python3 stdlib only). The DB is always opened
read-only via a ``file:...?mode=ro`` URI; observations.md is append-only with
the session id as idempotency key.

Usage:
    python3 scripts/executor_metrics.py extract \
        --db ~/.local/share/opencode/opencode.db \
        --project tangram-v2 \
        --out docs/proposals/executor-value-measurement/observations.md \
        [--since <epoch-ms|ISO8601>] \
        [--epochs "name:<T,name:T1-T2,name:>T2"] \
        [--price-override '{"flash":[in,out,cacheR],...}']

Semantics pinned by the design authority:
- verdict per bash part (output text): ``BUILD SUCCESSFUL`` -> ok;
  ``BUILD FAILED`` -> fail; ``exit code N`` with N != 0 -> fail; otherwise
  unknown. unknown neither increments nor resets a fail streak.
- status: first ``STATUS:\\s*(\\w+)`` match in the session's LAST text part
  (ordered by time_created); missing -> ``none``.
- ticket: first ``proposals/<p>/issues/<id>.md`` match in the FIRST text part.
- bash commands are normalized (trim, collapse whitespace, truncate to 120
  chars) before counting repetitions.
- epoch bounds are strict (``<T``, ``>T``); ranges ``T1-T2`` are inclusive.
- est_cost uses tier proxy prices $/M (input, output, cache read); tier is
  ``flash`` when the model id contains "flash", else ``flagship``.
"""

import argparse
import json
import re
import sqlite3
import sys
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_DB = Path.home() / ".local/share/opencode/opencode.db"

TICKET_RE = re.compile(r"proposals/[\w.-]+/issues/[\w.-]+\.md")
STATUS_RE = re.compile(r"STATUS:\s*(\w+)")
EXIT_CODE_RE = re.compile(r"exit code (\d+)")
WS_RE = re.compile(r"\s+")

# $/M proxy prices per tier: (input, output, cache_read) — requirement authority.
DEFAULT_PRICES = {
    "flash": (0.30, 2.50, 0.075),
    "flagship": (0.60, 2.20, 0.113),
}

COLUMNS = ("session", "ts", "dur_min", "model", "provider", "ticket", "epoch",
           "steps", "tools", "bash_n", "rep_max", "fail_streak",
           "in_tok", "out_tok", "cacheR_tok", "est_cost", "status")

HEADER_LINES = (
    "# Executor value observations",
    "",
    "Append-only per-session metrics for `flowforge-implementer` sessions, generated by",
    "`scripts/executor_metrics.py extract` (authorities: design.md d-extraction/d-cost).",
    "Do not edit rows by hand; re-run extract to append — the session id is the idempotency",
    "key. est_cost is a tier proxy price estimate, not an invoice figure.",
    "",
    "| " + " | ".join(COLUMNS) + " |",
    "|" + "---|" * len(COLUMNS),
)


class MetricsError(Exception):
    """User-facing extraction error (non-zero exit)."""


def open_ro(db_path):
    path = Path(db_path).expanduser()
    if not path.exists():
        raise MetricsError(f"database not found: {path}")
    uri = "file:" + urllib.parse.quote(str(path), safe="/:") + "?mode=ro"
    try:
        return sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        raise MetricsError(f"cannot open database read-only: {path}: {exc}") from exc


def check_schema(conn):
    try:
        names = {row[0] for row in
                 conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    except sqlite3.DatabaseError as exc:
        raise MetricsError(f"not a SQLite database: {exc}") from exc
    missing = {"session", "part"} - names
    if missing:
        raise MetricsError(
            "opencode DB missing table(s): " + ", ".join(sorted(missing)))


def classify_verdict(output_text):
    """ok / fail / unknown for one bash part's output text."""
    if not isinstance(output_text, str):
        return "unknown"
    if "BUILD SUCCESSFUL" in output_text:
        return "ok"
    if "BUILD FAILED" in output_text:
        return "fail"
    match = EXIT_CODE_RE.search(output_text)
    if match and int(match.group(1)) != 0:
        return "fail"
    return "unknown"


def normalize_command(cmd):
    """Trim, collapse whitespace, truncate to 120 chars (requirement constraint)."""
    return WS_RE.sub(" ", cmd.strip())[:120]


def parse_epochs(spec):
    """Parse "name:<T,name:T1-T2,name:>T2" into [(name, lo, hi)] bounds (ms)."""
    if not spec:
        return None
    epochs = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        name, sep, bound = chunk.partition(":")
        if not sep:
            raise MetricsError(f"bad epoch chunk, expected name:bound: {chunk!r}")
        name, bound = name.strip(), bound.strip()
        try:
            if bound.startswith("<"):
                epochs.append((name, None, int(bound[1:])))  # ts < hi
            elif bound.startswith(">"):
                epochs.append((name, int(bound[1:]) + 1, None))  # ts > bound
            else:
                lo, sep2, hi = bound.partition("-")
                if not sep2:
                    raise ValueError(bound)
                epochs.append((name, int(lo), int(hi) + 1))  # T1 <= ts <= T2
        except ValueError as exc:
            raise MetricsError(
                f"bad epoch bound, expected <T, T1-T2 or >T: {chunk!r}") from exc
    return epochs or None


def epoch_label(ts, epochs):
    if not epochs:
        return "-"
    for name, lo, hi in epochs:
        if lo is not None and ts < lo:  # range lower bound inclusive
            continue
        if hi is not None and ts >= hi:  # '< T' strict, range upper inclusive
            continue
        return name
    return "-"


def parse_prices(override_json):
    if not override_json:
        return None
    try:
        obj = json.loads(override_json)
    except ValueError as exc:
        raise MetricsError(f"--price-override is not valid JSON: {exc}") from exc
    if not isinstance(obj, dict):
        raise MetricsError("--price-override must be a JSON object tier -> [in, out, cacheR]")
    prices = {}
    for tier, vals in obj.items():
        if not isinstance(vals, list) or len(vals) != 3:
            raise MetricsError(f"--price-override tier {tier!r} must be [in, out, cacheR]")
        try:
            prices[tier] = tuple(float(v) for v in vals)
        except (TypeError, ValueError) as exc:
            raise MetricsError(
                f"--price-override tier {tier!r} must be numeric") from exc
    return prices


def parse_since(value):
    if value is None:
        return None
    text = value.strip()
    if re.fullmatch(r"\d{10,}", text):
        return int(text)
    try:
        dt = datetime.fromisoformat(text)
    except ValueError as exc:
        raise MetricsError(
            f"--since must be epoch-ms or ISO8601, got: {value!r}") from exc
    if dt.tzinfo is None:
        dt = dt.astimezone()
    return int(dt.timestamp() * 1000)


def fmt_ts(ms):
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).astimezone().isoformat(
        timespec="seconds")


def _session_metrics(conn, sess_row, prices, epochs):
    (sid, model_json, _directory, ti, to, tcr, tc, tu) = sess_row
    model_id = provider = "-"
    try:
        model = json.loads(model_json) if model_json else {}
        if isinstance(model, dict):
            model_id = str(model.get("id") or "-")
            provider = str(model.get("providerID") or "-")
    except ValueError:
        pass

    steps = tools = bash_n = 0
    cmd_counts = {}
    verdicts = []
    first_text = None
    last_text = None
    corrupt = 0
    query = ("SELECT data FROM part WHERE session_id=? "
             "ORDER BY time_created, rowid")
    for (raw,) in conn.execute(query, (sid,)):
        try:
            data = json.loads(raw) if raw else None
        except ValueError:
            corrupt += 1
            continue
        if not isinstance(data, dict):
            corrupt += 1
            continue
        ptype = data.get("type")
        if ptype == "step-start":
            steps += 1
        elif ptype == "tool":
            tools += 1
            if data.get("tool") != "bash":
                continue
            bash_n += 1
            state = data.get("state")
            if not isinstance(state, dict):
                state = {}
            cmd = state.get("input")
            if isinstance(cmd, dict):
                cmd = cmd.get("command")
            if isinstance(cmd, str) and cmd.strip():
                key = normalize_command(cmd)
                cmd_counts[key] = cmd_counts.get(key, 0) + 1
            output = state.get("output")
            verdicts.append(classify_verdict(output))
        elif ptype == "text":
            txt = data.get("text")
            txt = txt if isinstance(txt, str) else ""
            if first_text is None:
                first_text = txt
            last_text = txt

    streak = current = 0
    for verdict in verdicts:
        if verdict == "fail":
            current += 1
            streak = max(streak, current)
        elif verdict == "ok":
            current = 0  # unknown is skipped: neither counts nor resets (design)

    ti = ti or 0
    to = to or 0
    tcr = tcr or 0
    tier = "flash" if "flash" in model_id.lower() else "flagship"
    pin, pout, pcr = prices[tier]
    est_cost = round(ti / 1e6 * pin + to / 1e6 * pout + tcr / 1e6 * pcr, 4)
    ticket_match = first_text and TICKET_RE.search(first_text)
    status_match = last_text and STATUS_RE.search(last_text)
    metrics = {
        "session": sid,
        "ts": fmt_ts(tc),
        "dur_min": round((tu - tc) / 60000, 1),
        "model": model_id,
        "provider": provider,
        "ticket": ticket_match.group(0) if ticket_match else "-",
        "epoch": epoch_label(tc, epochs),
        "steps": steps,
        "tools": tools,
        "bash_n": bash_n,
        "rep_max": max(cmd_counts.values(), default=0),
        "fail_streak": streak,
        "in_tok": ti,
        "out_tok": to,
        "cacheR_tok": tcr,
        "est_cost": est_cost,
        "status": status_match.group(1) if status_match else "none",
    }
    return metrics, corrupt


def collect_metrics(conn, project, since_ms=None, prices=None, epochs=None):
    """Return (rows, corrupt_total): one metrics dict per matching session,
    ordered by time_created ascending."""
    merged = dict(DEFAULT_PRICES)
    merged.update(prices or {})
    query = ("SELECT id, model, directory, tokens_input, tokens_output, "
             "tokens_cache_read, time_created, time_updated FROM session "
             "WHERE agent='flowforge-implementer' AND directory LIKE ? ")
    args = ["%" + project]
    if since_ms is not None:
        query += "AND time_created >= ? "
        args.append(since_ms)
    query += "ORDER BY time_created"
    rows, corrupt_total = [], 0
    for sess_row in conn.execute(query, args):
        metrics, corrupt = _session_metrics(conn, sess_row, merged, epochs)
        corrupt_total += corrupt
        rows.append(metrics)
    return rows, corrupt_total


def format_row(metrics):
    cells = [str(metrics[col]).replace("|", "\\|").replace("\n", " ")
             for col in COLUMNS]
    return "| " + " | ".join(cells) + " |"


def append_idempotent(out_path, metrics):
    """Append rows whose session id is not already present; write the table
    header when the file is missing or empty. Returns (appended, skipped)."""
    path = Path(out_path)
    content = path.read_text(encoding="utf-8") if path.exists() else None
    existing_lines = content.splitlines() if content is not None else []
    new_rows = [m for m in metrics
                if not any(m["session"] in line for line in existing_lines)]
    with open(path, "a", encoding="utf-8", newline="\n") as handle:
        if not content:  # missing or empty file -> header
            for line in HEADER_LINES:
                handle.write(line + "\n")
        elif not content.endswith("\n"):
            handle.write("\n")
        for m in new_rows:
            handle.write(format_row(m) + "\n")
    return len(new_rows), len(metrics) - len(new_rows)


def build_parser():
    parser = argparse.ArgumentParser(
        prog="executor_metrics.py",
        description="Extract flowforge-implementer session metrics from the "
                    "opencode DB (read-only).")
    sub = parser.add_subparsers(dest="command", required=True)
    extract = sub.add_parser(
        "extract", help="extract metrics and append to observations.md")
    extract.add_argument("--db", default=str(DEFAULT_DB),
                         help="opencode SQLite DB path (default: %(default)s; "
                              "always opened read-only)")
    extract.add_argument("--project", required=True,
                         help="project directory suffix, e.g. tangram-v2")
    extract.add_argument("--out", required=True,
                         help="observations.md path (append-only)")
    extract.add_argument("--since", default=None,
                         help="only sessions with time_created >= TS "
                              "(epoch ms or ISO8601; inclusive)")
    extract.add_argument("--epochs", default=None,
                         help='epoch spec "name:<T,name:T1-T2,name:>T2" in epoch ms')
    extract.add_argument("--price-override", default=None,
                         help="JSON object tier -> [in, out, cacheR] $/M "
                              "over the built-in proxy prices")
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    try:
        epochs = parse_epochs(args.epochs)
        prices = parse_prices(args.price_override)
        since = parse_since(args.since)
        conn = open_ro(args.db)
        try:
            check_schema(conn)
            metrics, corrupt = collect_metrics(conn, args.project, since_ms=since,
                                               prices=prices, epochs=epochs)
        finally:
            conn.close()
    except MetricsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if corrupt:
        print(f"warn: skipped {corrupt} part row(s) with unreadable data JSON",
              file=sys.stderr)
    try:
        appended, skipped = append_idempotent(args.out, metrics)
    except OSError as exc:
        print(f"error: cannot write observations file {args.out}: {exc}",
              file=sys.stderr)
        return 1
    print(f"extract: {len(metrics)} session(s) matched, appended {appended}, "
          f"skipped {skipped} existing -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
